# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_key.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(241, 91)
        self.key_lineEdit = QtWidgets.QLineEdit(Form)
        self.key_lineEdit.setGeometry(QtCore.QRect(10, 10, 221, 31))
        self.key_lineEdit.setObjectName("key_lineEdit")
        self.save_pushButton = QtWidgets.QPushButton(Form)
        self.save_pushButton.setGeometry(QtCore.QRect(22, 47, 81, 31))
        self.save_pushButton.setObjectName("save_pushButton")
        self.save_pushButton_2 = QtWidgets.QPushButton(Form)
        self.save_pushButton_2.setGeometry(QtCore.QRect(130, 47, 81, 31))
        self.save_pushButton_2.setObjectName("save_pushButton_2")

        self.retranslateUi(Form)
        self.save_pushButton.clicked.connect(Form.setkey)
        self.save_pushButton_2.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.save_pushButton.setText(_translate("Form", "保存"))
        self.save_pushButton_2.setText(_translate("Form", "退出"))
